version: "3.9"

services:
  cassandra:
    image: cassandra:4.0.3
    container_name: gyunny_cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=512M"
      - "HEAP_NEWSIZE=256M"
    restart: always
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data:
    driver: local
